fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"

  repositories:
# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    nfs: "https://github.com/echocat/puppet-nfs.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
  symlinks:
    profile_apache: "#{source_dir}"
