fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    nfs: "https://github.com/derdanne/puppet-nfs.git"
  symlinks:
    profile_apache: "#{source_dir}"
